name: HolaMundo
options:
  bundleIdPrefix: com.usuario
targets:
  HolaMundo:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - HolaMundo
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.usuario.holamundo
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"